project:
  type: website
  preview:
    port: 9999
    browser: false
  resources:
    - "assets/**"
    - ads.txt
    - "*.html"
    - "tree.png"
metadata-files:
  - _announcement.yml
execute:
  freeze: auto
website:
  title: "Luozxçš„æ•°å­—èŠ±å›­ðŸŒ³"
  site-url: "https://luozx.org"
  description: "Hihi, welcome.!"
  reader-mode: false
  repo-url: "https://github.com/0ptimista/Garden"
  repo-actions: [source]
  favicon: "/tree.png"
  bread-crumbs: true
  open-graph:
    image: "/tree.png"
    locale: zh_CN
  twitter-card:
    creator: "@luozxdotorg"
    card-style: summary
    image: "/tree.png"
  navbar:
    left:
      - text: About...
        href: pages/about.qmd
      - text: ToolBox
        href: pages/toolbox.qmd
    right:
      - icon: "bi bi-twitter-x"
        href: https://x.com/luozxdotorg
        aria-label: Twitterxml
      - icon: "bi bi-telegram"
        href: https://t.me/backyardofthatman
        aria-label: Telegram channel
      - icon: github
        href: https://github.com/0ptimista
        aria-label: GitHub
      - icon: rss
        href: https://luozx.org/index.xml
        aria-label: Rss Feed
  page-footer:
    center: |
      <a href="/privacy">ç«™å†…å¹¿å‘Š</a>
  back-to-top-navigation: true

author: "Luozx"
adsense:
  publisher-id: ca-pub-9560220640659728
filters:
  - adsense
lang: zh
date-format: "YYYY-MM-DD HH:mm"
license: "CC BY-NC-SA"
copyright: 
  holder: Luozx
funding: 
  statement: "The author(s) received no specific funding for this work."

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    # template-partials:
    #   - title-block.html
    theme:
      # light: [solar,style-light.scss]
      # light: [zephyr,style-light.scss]
      light: [cosmo,style-light.scss]
      dark: [cosmo,style-dark.scss]
    highlight-style:
      dark: codehighlight-dark.json
    toc: true
    canonical-url: true
    reference-location: margin
    lightbox: true
    default-image-extension: ""
    include-in-header:
      - file: include/tagmanager-header.html
      - file: include/google-fonts.html
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="713c9485-413b-4a68-91d3-3a32d926297f"></script>
    include-before-body:
      - include/ko-fi.html
      - include/tagmanager-body.html
    include-after-body:
      - include/share-button.html

